### ISSUE TITLE
this does not work on android lollipop

### ISSUE THREAD

**Issue by pcca-matrix** [mebibou/cordova-plugin-backlight#1]
error is :
/sys/class/backlight_show/backlight_status: open failed: ENOENT (No such file or directory)

**Comment by mebibou** [comment]
could you give me information on the hardware? i.e. motherboard and all

**Comment by pcca-matrix** [comment]
it's a cheap tablet here is spec.
http://www.tablet-user.fr/test/test-carrefour-touch-tablet-5.html

**Comment by badis** [comment]
Same thing happened for my device :  Android 6.0 APIs (API level 23) 

/sys/class/backlight_show/backlight_status: open failed: ENOENT (No such file or directory)

**Comment by jstephancc** [comment]
I have the same issue on CAT S30, Android 5.1.

/sys/class/backlight_show/backlight_status: open failed: ENOENT (No such file or directory)

**Comment by mebibou** [comment]
actually every device will have different drivers for this, so you will need to do a PR if you want your device to be supported

**Comment by jasperkuperus** [comment]
Same issue on Samsung Tab A:

`/sys/class/backlight_show/backlight_status: open failed: ENOENT (No such file or directory)
undefined`

**Comment by milankragujevic** [comment]
On Allwinner devices (i.e. cheap tablets), the proper path is `/sys/class/disp/disp/attr/lcd`. This turn on or off the LEDs, the LCD still shows the picture (you can point a flashlight at it and see the picture while the backlight is off).

**Comment by brandon-pereira** [comment]
This is all new to me, but my device path was slightly different. To find my path, I ran `adb shell` then you can navigate around the filesystem till you find a file which has either `1` or `0` in it. My path was very similar to @milankragujevic  but the path was `/sys/class/disp/disp/attr/disp`
